# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5193:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=HealthCareDb;User ID=docker;Password=Sooyoung@17;TrustServerCertificate=True;Encrypt=False
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge